### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory When loading `timm.create_model("resnet18_cifar10", pretrained=True)`

### ISSUE THREAD

**Issue by DeepOceanDeep** [edadaltocg/detectors#19]
Hi @edadaltocg  thanks for sharing the codes. How to inference of cifar10 test set via your pretrained models?

I'm trying to load and normally evaluate with `resent18_cifar10`. I have a VRAM 16 and Memory 64. No matter what eval batch size I use, eventually this throw an Out-of-Memory error!
```
import detectors
import timm

model = timm.create_model("resnet18_cifar10", pretrained=True)
```

But when I use timm from hf and even batch size 1024 it's not throwing memory error. Any thought?  

```
import timm
m = timm.create_model('resnet18', pretrained=True, num_classes=10)
```

Thank you

**Comment by edadaltocg** [comment]
Hi @DeepOceanDeep

Can you check the input image size and the input pre-processing function, please? 

The first convolutional layer of the resnet18_cifar10 model has a smaller kernel size given the small size of Cifar images, (3,3) vs (7,7) of timm. So, if you input a larger size image, it is possible that the intermediate representations are larger than the available VRAM.

**Comment by DeepOceanDeep** [comment]
Thanks @edadaltocg  I'm using cifar10 and size 32

```
from torchvision.transforms import v2
def ld_cifar10():
    """Load training and test data."""
    train_transforms = v2.Compose(
        [v2.ToImage(),
         v2.ToDtype(torch.float32, scale=True),
         v2.Resize((32,32), antialias=True),
         v2.RandomCrop(32, padding=4),
         v2.RandomHorizontalFlip(),
         normalize
         ]
    )

    test_transforms = v2.Compose(
        [v2.ToImage(),
         v2.ToDtype(torch.float32, scale=True),
         normalize
         ]
    )
    train_dataset = torchvision.datasets.CIFAR10(
        root="C:/datasets/cifar10", train=True, transform=train_transforms, download=False
    )
    test_dataset = torchvision.datasets.CIFAR10(
        root="C:/datasets/cifar10", train=False, transform=test_transforms, download=False
    )
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=128, shuffle=True, num_workers=2, drop_last=True
    )
    test_loader = torch.utils.data.DataLoader(
        test_dataset, batch_size=128, shuffle=False, num_workers=2, drop_last=True
    )
    return EasyDict(train=train_loader, test=test_loader)
```

**Comment by DeepOceanDeep** [comment]
It does not give Out-of-Memory right away. But after a couple of minutes, I can see that my Memory is running out, not the GPU memory.

**Comment by DeepOceanDeep** [comment]
@edadaltocg any thought on this? or possible way to use checkpoints?

**Comment by edadaltocg** [comment]
The checkpoints are available at `https://huggingface.co/edadaltocg/resnet18_cifar10`.

FOr checkpoints on other models you can check the models section at `https://huggingface.co/edadaltocg`.

**Comment by DeepOceanDeep** [comment]
Thanks!

**Comment by edadaltocg** [comment]
Could you also share the `transform_test`, please?

**Comment by DeepOceanDeep** [comment]
Thanks @edadaltocg  This is my transform

`
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
])

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)
testloader = torch.utils.data.DataLoader(testset, batch_size=128, shuffle=False, num_workers=2)`

**Comment by DeepOceanDeep** [comment]
I used the following and it shows 94% now. Very interesting that a few floating point numbers changes the results this much! Thanks again & I'll make sure to cite the repo for the checkpoints used. 💯 
```
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(   mean=[0.491, 0.482, 0.446],
                            std=[0.247, 0.243, 0.261]),
])
```
